# IMPORTANT: BUILD THE BASE IMAGE (from .base-image/) FIRST

name: "Day Rater"

services:
  # details in the build-and-run.md in db_handler/
  db-handler:
    build:
      context: "db_handler/"
      dockerfile: "Docker/Dockerfile"
    container_name: "db_handler"
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      INTERNAL_DB_PATH: "/db/db.csv"
      DEBUG: "False"
    volumes:
      - "/Users/Misha/Documents/python_projects/day-rater-db/db.csv:/db/db.csv"

    develop:
      watch:
        - path: "db_handler/db_handler.py"
          target: "/app/db_handler/db_handler.py"
          action: sync+restart

        - path: "db_handler/utility.py"
          target: "/app/db_handler/utility.py"
          action: sync+restart

        - path: "Docker/Dockerfile"
          action: rebuild

        - path: "db_handler/tests/test_utility.py"
          target: "/app/db_handler/tests/test_utility.py"
          action: sync+restart

        - path: "db_handler/tests/test_api.py"
          target: "/app/db_handler/tests/test_api.py"
          action: sync+restart

  # details in the build-and-run.md in data_analyzer/
  data-analyzer:
    build:
      context: "data_analyzer/"
      dockerfile: "Docker/Dockerfile"

    container_name: "data-analyser"
    ports:
      - "127.0.0.1:8001:8000"

    environment:
      CONTAINER_NAME: "data_analyzer"

    develop:
      watch:
        - path: "data_analyzer/data_analyzer.py"
          target: "/app/data_analyzer/data_analyzer.py"
          action: sync+restart

        - path: "data_analyzer/routing.py"
          target: "/app/data_analyzer/routing.py"
          action: sync+restart

        - path: "Docker/Dockerfile"
          action: rebuild
