# IMPORTANT: BUILD THE BASE IMAGE (from .base-image/) FIRST

name: "Day Rater"

services:
  # details in the build-and-run.md in db-handler/
  db-handler:
    build:
      context: "db-handler/"
      dockerfile: "Docker/Dockerfile"
    container_name: "db-handler"
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      INTERNAL_DB_PATH: "/db/db.csv"
    volumes:
      - "/Users/Misha/Documents/python_projects/day-rater-db/db.csv:/db/db.csv"

    develop:
      watch:
        - path: "db-handler/db-handler.py"
          target: "/app/db-handler/db-handler.py"
          action: sync+restart

        - path: "db-handler/utility.py"
          target: "/app/db-handler/utility.py"
          action: sync+restart